export const categories = {
  essentials: [
    { name: "egg", selected: false },
    { name: "garlic", selected: false },
    { name: "milk", selected: false },
    { name: "onion", selected: false },
    { name: "sugar", selected: false },
    { name: "flour", selected: false },
    { name: "olive oil", selected: false },
    { name: "rice", selected: false },
    { name: "soy sauce", selected: false },
    { name: "bread", selected: false },
    { name: "potato", selected: false },
    { name: "tomato", selected: false },
    { name: "bell pepper", selected: false },
    { name: "honey", selected: false },
    { name: "chicken breast", selected: false },
    { name: "chicken thigh", selected: false },
  ],
  vegetables: [
    { name: "onion", selected: false },
    { name: "garlic", selected: false },
    { name: "tomato", selected: false },
    { name: "onion", selected: false },
    { name: "broccoli", selected: false },
    { name: "flour", selected: false },
    { name: "spinach", selected: false },
    { name: "asparagus", selected: false },
    { name: "lettuce", selected: false },
    { name: "green beans", selected: false },
    { name: "sweet potato", selected: false },
    { name: "potato", selected: false },
    { name: "bell pepper", selected: false },
    { name: "zucchini", selected: false },
    { name: "chile pepper", selected: false },
  ],
  fruits: [
    { name: "lemon", selected: false },
    { name: "apple", selected: false },
    { name: "tomato", selected: false },
    { name: "lime", selected: false },
    { name: "orange", selected: false },
    { name: "grape", selected: false },
    { name: "kiwi", selected: false },
    { name: "grapefruit", selected: false },
    { name: "passion fruit", selected: false },
    { name: "melon", selected: false },
    { name: "sweet potato", selected: false },
    { name: "pear", selected: false },
    { name: "peach", selected: false },
    { name: "craisins", selected: false },
    { name: "watermelon", selected: false },
  ],
};
